### ISSUE TITLE
code=UNPREDICTABLE_GAS_LIMIT

### ISSUE THREAD

**Issue by pamarthisai** [jamesbachini/DEX-Arbitrage#20]
hi iam trying on fantom but code=UNPREDICTABLE_GAS_LIMIT error can u pls guide me

**Comment by jamesbachini** [comment]
It's just an error which means the transaction will fail. Likely an incorrect router or token address.

More info here: https://github.com/jamesbachini/DEX-Arbitrage/issues/13

**Comment by pamarthisai** [comment]
thanks for fast response but i did not change any addresses from the repo and i checked checksum also all are checksumed can u pls help it is very usefull to me please

**Comment by jamesbachini** [comment]
For some reason the transaction you are trying to execute is failing which is why you are getting the gas limit error. There's nothing else to go off to give you more direction in finding the bug. Make sure the .env wallet is funded to pay transaction fees as Aurora introduced transaction fees. Double check network details and contract addresses. There is a full tutorial here to see if there is anything missing: https://jamesbachini.com/dex-arbitrage/
